### ISSUE TITLE
Big tables & filters appear strangely

### ISSUE THREAD

**Issue by sephii** [divio/djangocms-admin-style#270]
As you can see in the following screenshot the table gets 2 inner scrollbars, while the filters part gets another vertical scrollbar, and the whole page also has a (disabled) scrollbar.

![2015-12-04-175758_1588x790_scrot](https://cloud.githubusercontent.com/assets/754333/11595672/e09ce83a-9ab0-11e5-9007-80c4b0a0f4a9.jpg)

I think this is quite confusing. Wouldn't there be a better way of displaying such information?

**Comment by FinalAngel** [comment]
@sephii the filter gets limited for a certain height, otherwise parts might be cut off when to large and on overflow mode.

The horizontal line on your data is also valid, as tables have limited space as well. Yet the vertical scrollbar is curious. Might I ask what system / browser / cms/django version you are using?

**Comment by sephii** [comment]
Browser is Iceweasel (Firefox) 38.2.1, DjangoCMS 3.2.0, Django 1.8.7 and django-admin-style 1.0.7. The issue also appears on Chromium 46.0.

**Comment by lory87** [comment]
@sephii The vertical scrollbar on list is removed and will be in the next release.

**Comment by sephii** [comment]
Thanks!
